//! Startup commands service.

use crate::models::startup_command::StartupCommand;
use std::fs;
use std::path::Path;

fn get_home_dir() -> String {
    std::env::var("HOME").unwrap_or_else(|_| "/home/i4104".to_string())
}

/// Retrieves list of autostart commands.
pub fn get_startup_commands() -> Vec<StartupCommand> {
    let home = get_home_dir();
    let config_path = Path::new(&home).join(".config/babydra/autostart.conf");
    let mut commands = Vec::new();

    if let Ok(content) = fs::read_to_string(&config_path) {
        let mut id_counter = 1;
        for line in content.lines() {
            let trim = line.trim();
            if trim.is_empty() || trim.starts_with('#') {
                continue;
            }
            if trim.starts_with("exec-once") {
                if let Some((_, cmd)) = trim.split_once('=') {
                    commands.push(StartupCommand {
                        id: id_counter,
                        command: cmd.trim().to_string(),
                    });
                    id_counter += 1;
                }
            } else {
                commands.push(StartupCommand {
                    id: id_counter,
                    command: trim.to_string(),
                });
                id_counter += 1;
            }
        }
    }

    if commands.is_empty() {
        commands.push(StartupCommand { id: 1, command: "waybar".to_string() });
        commands.push(StartupCommand { id: 2, command: "dunst".to_string() });
    }

    commands
}

/// Saves autostart commands.
pub fn save_startup_commands(commands: &[StartupCommand]) -> Result<(), String> {
    let home = get_home_dir();
    let config_path = Path::new(&home).join(".config/babydra/autostart.conf");

    if let Some(parent) = config_path.parent() {
        let _ = fs::create_dir_all(parent);
    }

    let mut content = String::from("# Custom autostart commands\n# Auto-generated by Settings\n\n");
    for cmd in commands {
        if !cmd.command.trim().is_empty() {
            content.push_str(&format!("exec-once = {}\n", cmd.command.trim()));
        }
    }

    fs::write(config_path, content).map_err(|e| e.to_string())
}
