//! Startup commands service (Labwc autostart).

use crate::models::startup_command::StartupCommand;
use std::fs;
use std::path::{Path, PathBuf};

#[cfg(unix)]
use std::os::unix::fs::PermissionsExt;

fn get_home_dir() -> String {
    std::env::var("HOME").unwrap_or_else(|_| "/home/i4104".to_string())
}

/// Gets the path to the labwc autostart configuration file.
fn get_autostart_path() -> PathBuf {
    let home = get_home_dir();
    let user_config = Path::new(&home).join(".config/labwc/autostart");
    if user_config.exists() {
        return user_config;
    }

    // Check project workspace fallback
    let local_config = Path::new("configs/labwc/autostart");
    if local_config.exists() {
        return local_config.to_path_buf();
    }

    user_config
}

/// Retrieves list of autostart commands from labwc autostart file.
pub fn get_startup_commands() -> Vec<StartupCommand> {
    let config_path = get_autostart_path();
    let mut commands = Vec::new();

    if let Ok(content) = fs::read_to_string(&config_path) {
        let mut id_counter = 1;
        for line in content.lines() {
            let trim = line.trim();
            if trim.is_empty() || trim.starts_with('#') {
                continue;
            }
            if trim.starts_with("exec-once") {
                if let Some((_, cmd)) = trim.split_once('=') {
                    commands.push(StartupCommand {
                        id: id_counter,
                        command: cmd.trim().to_string(),
                    });
                    id_counter += 1;
                }
            } else {
                commands.push(StartupCommand {
                    id: id_counter,
                    command: trim.to_string(),
                });
                id_counter += 1;
            }
        }
    }

    if commands.is_empty() {
        commands.push(StartupCommand {
            id: 1,
            command: "babydra-switcher --daemon &".to_string(),
        });
        commands.push(StartupCommand {
            id: 2,
            command: "~/.local/bin/babydra-panel &".to_string(),
        });
    }

    commands
}

/// Saves autostart commands to labwc autostart file.
pub fn save_startup_commands(commands: &[StartupCommand]) -> Result<(), String> {
    let home = get_home_dir();
    let user_config = Path::new(&home).join(".config/labwc/autostart");

    if let Some(parent) = user_config.parent() {
        let _ = fs::create_dir_all(parent);
    }

    let mut content = String::from("#!/bin/bash\n# Autostart configuration for labwc with BabyDra shell\n# Auto-generated by Settings\n\n");
    for cmd in commands {
        let trimmed = cmd.command.trim();
        if !trimmed.is_empty() {
            content.push_str(&format!("{}\n", trimmed));
        }
    }

    fs::write(&user_config, &content).map_err(|e| e.to_string())?;

    #[cfg(unix)]
    {
        let _ = fs::set_permissions(&user_config, fs::Permissions::from_mode(0o755));
    }

    // Also sync to workspace configs/labwc/autostart if present
    let local_config = Path::new("configs/labwc/autostart");
    if local_config.exists() && local_config != user_config {
        let _ = fs::write(local_config, &content);
        #[cfg(unix)]
        {
            let _ = fs::set_permissions(local_config, fs::Permissions::from_mode(0o755));
        }
    }

    Ok(())
}
