[package]
name = "babydra-greeter"
edition = "2024"
version.workspace = true

[dependencies]
gtk4 = { version = "0.9", features = ["v4_10"] }
gtk4-layer-shell = "0.4.0"
tokio = { version = "1.0", features = ["full", "rt-multi-thread"] }
tracing = "0.1"
dirs = "5.0"
glib = "0.20"
greetd_ipc = { version = "0.10", features = ["codec"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
babydra-common = { workspace = true }
babydra-utils = { workspace = true }
