[package]
name = "babydra-greeter"
edition = "2024"
version.workspace = true

[dependencies]
gtk4 = { workspace = true }
gtk4-layer-shell = { workspace = true }
tokio = { workspace = true }
tracing = "0.1"
dirs = { workspace = true }
glib = { workspace = true }
greetd_ipc = { version = "0.10", features = ["codec"] }
serde = { workspace = true }
serde_json = { workspace = true }
babydra-core = { workspace = true }
babydra-ui-kit = { workspace = true }
