[package]
name = "babydra-ui-kit"
version.workspace = true
edition = "2021"

[dependencies]
babydra-core = { workspace = true }
babydra-theme = { workspace = true }
gtk4 = { workspace = true }
glib = { workspace = true }
gio = { workspace = true }
chrono = { workspace = true }
tokio = { workspace = true }
gtk4-layer-shell = { workspace = true }
gdk-pixbuf = { workspace = true }
gdk4 = { workspace = true }
cairo-rs = { workspace = true }
kamadak-exif = "0.5"
serde_json = { workspace = true }
tracing = "0.1"

