[package]
name = "babydra-desktop"
version.workspace = true
edition = "2021"

[dependencies]
babydra-core = { workspace = true }
babydra-ui-kit = { workspace = true }

# GUI & Layer Shell
gtk4 = { workspace = true }
gtk4-layer-shell = { workspace = true }

# Async & utilities
tokio = { workspace = true }
tracing = "0.1"
glib = { workspace = true }
gdk4 = { workspace = true }
gdk-pixbuf = { workspace = true }
gio = { workspace = true }
cairo-rs = { workspace = true }
dirs = { workspace = true }
