pub mod wifi;
pub mod volume;
pub mod backlight;
pub mod storage;
pub mod clean;
pub mod power;
pub mod auth;
pub mod monitor;
pub mod bluetooth;
pub mod vpn;
pub mod network;
pub mod gsettings;
pub mod battery;
pub mod display;
pub mod theme;
pub mod startup;
pub mod updates;

pub use gsettings::set_gsettings_color_scheme;
