//! Predefined BabyDra crate system shortcuts catalog.

/// Definition of a standard BabyDra crate system shortcut.
pub struct SystemCrateDef {
    pub id: &'static str,
    pub crate_name: &'static str,
    pub name_key: &'static str,
    pub description_key: &'static str,
    pub command: &'static str,
    pub default_modifiers: &'static str,
    pub default_key: &'static str,
}

/// Catalog of all BabyDra crates and their default global shortcuts.
pub const SYSTEM_CRATE_CATALOG: &[SystemCrateDef] = &[
    SystemCrateDef {
        id: "launcher",
        crate_name: "babydra-launcher",
        name_key: "settings.keybind_launcher",
        description_key: "settings.keybind_launcher_desc",
        command: "~/.local/bin/babydra-launcher",
        default_modifiers: "W",
        default_key: "q",
    },
    SystemCrateDef {
        id: "switcher",
        crate_name: "babydra-switcher",
        name_key: "settings.keybind_switcher",
        description_key: "settings.keybind_switcher_desc",
        command: "~/.local/bin/babydra-switcher",
        default_modifiers: "A",
        default_key: "Tab",
    },
    SystemCrateDef {
        id: "screenshot",
        crate_name: "babydra-screenshot",
        name_key: "settings.keybind_screenshot",
        description_key: "settings.keybind_screenshot_desc",
        command: "~/.local/bin/babydra-screenshot",
        default_modifiers: "W",
        default_key: "F12",
    },
    SystemCrateDef {
        id: "screenshot_area",
        crate_name: "babydra-screenshot",
        name_key: "settings.keybind_screenshot_area",
        description_key: "settings.keybind_screenshot_area_desc",
        command: "~/.local/bin/babydra-screenshot",
        default_modifiers: "W-S",
        default_key: "s",
    },
    SystemCrateDef {
        id: "recorder_ui",
        crate_name: "babydra-recorder",
        name_key: "settings.keybind_recorder_ui",
        description_key: "settings.keybind_recorder_ui_desc",
        command: "~/.local/bin/babydra-recorder --ui",
        default_modifiers: "W",
        default_key: "r",
    },
    SystemCrateDef {
        id: "recorder_toggle",
        crate_name: "babydra-recorder",
        name_key: "settings.keybind_recorder_toggle",
        description_key: "settings.keybind_recorder_toggle_desc",
        command: "~/.local/bin/babydra-recorder --toggle",
        default_modifiers: "W-A",
        default_key: "r",
    },
    SystemCrateDef {
        id: "recorder_area",
        crate_name: "babydra-recorder",
        name_key: "settings.keybind_recorder_area",
        description_key: "settings.keybind_recorder_area_desc",
        command: "~/.local/bin/babydra-recorder --area",
        default_modifiers: "W-S",
        default_key: "r",
    },
    SystemCrateDef {
        id: "lock",
        crate_name: "babydra-lock",
        name_key: "settings.keybind_lock",
        description_key: "settings.keybind_lock_desc",
        command: "~/.local/bin/babydra-lock",
        default_modifiers: "W",
        default_key: "l",
    },
    SystemCrateDef {
        id: "settings",
        crate_name: "babydra-settings",
        name_key: "settings.keybind_settings",
        description_key: "settings.keybind_settings_desc",
        command: "~/.local/bin/babydra-settings",
        default_modifiers: "W",
        default_key: "i",
    },
    SystemCrateDef {
        id: "explore",
        crate_name: "babydra-explore",
        name_key: "settings.keybind_explore",
        description_key: "settings.keybind_explore_desc",
        command: "~/.local/bin/babydra-explore",
        default_modifiers: "W",
        default_key: "e",
    },
];
