[package]
name = "babydra-workspace"
version.workspace = true
edition = "2021"

[lib]
name = "babydra_workspace"
path = "src/lib.rs"

[[bin]]
name = "babydra-workspace"
path = "src/main.rs"

[dependencies]
babydra-core = { workspace = true }
babydra-ui-kit = { workspace = true }

# GUI
gtk4 = { workspace = true }
glib = { workspace = true }
gio = { workspace = true }
